fileVersion: 1
id: "2"
mappingDefinitions:
  SAMPLE:
    database: COALESCE_SAMPLE_DATABASE
    schema: TPCH_SF001
  WORK:
    database: EVAN_DEV_EDW
    schema: PUBLIC
name: New Environment
type: Environment
